globals:
  - id: active_slot
    type: int
    initial_value: '254'  # 254 represents "External"

# Define the select component
select:
  - platform: template
    name: "Active Slot"
    id: active_slot_select
    options:
      - "External"
      - "1"
      - "2"
      - "3"
      - "4"
    initial_option: "External"
    optimistic: true
    set_action:
      then:
        - lambda: |-
            if (x == "External") id(active_slot) = 254;
            else if (x == "1") id(active_slot) = 0;
            else if (x == "2") id(active_slot) = 1;
            else if (x == "3") id(active_slot) = 2;
            else if (x == "4") id(active_slot) = 3;
        - script.execute: select_slot
    state_topic: null
    web_server:
      sorting_group_id: sorting_group_filament_settings
      sorting_weight: 190

script:
  - id: select_slot
    then:
      - switch.turn_off: slot_1_switch
      - switch.turn_off: slot_2_switch
      - switch.turn_off: slot_3_switch
      - switch.turn_off: slot_4_switch
      - lambda: |-
          switch (id(active_slot)) {
            case 0: 
              id(slot_1_switch).turn_on(); 
              id(set_led_white).execute(0);
              id(set_led_off).execute(1);
              id(set_led_off).execute(2);
              id(set_led_off).execute(3);
              break;
            case 1: 
              id(slot_2_switch).turn_on(); 
              id(set_led_white).execute(1);
              id(set_led_off).execute(0);
              id(set_led_off).execute(2);
              id(set_led_off).execute(3);
              break;
            case 2: 
              id(slot_3_switch).turn_on(); 
              id(set_led_white).execute(2);
              id(set_led_off).execute(0);
              id(set_led_off).execute(1);
              id(set_led_off).execute(3);
              break;
            case 3: 
              id(slot_4_switch).turn_on(); 
              id(set_led_white).execute(3);
              id(set_led_off).execute(0);
              id(set_led_off).execute(1);
              id(set_led_off).execute(2);
              break;
            // No action needed for 254 (External) as all switches are already off
          }

switch:
  - platform: template
    name: "Slot 1 Switch"
    id: slot_1_switch
    internal: true
    optimistic: true
    state_topic: null
  - platform: template
    name: "Slot 2 Switch"
    id: slot_2_switch
    internal: true
    optimistic: true
    state_topic: null
  - platform: template
    name: "Slot 3 Switch"
    id: slot_3_switch
    internal: true
    optimistic: true
    state_topic: null
  - platform: template
    name: "Slot 4 Switch"
    id: slot_4_switch
    internal: true
    optimistic: true
    state_topic: null

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
      inverted: true
    name: "Slot 1 Button"
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      then:
        - lambda: |-
            if (id(active_slot) == 0) {
              id(active_slot) = 254;
              id(active_slot_select).publish_state("External");
            } else {
              id(active_slot) = 0;
              id(active_slot_select).publish_state("1");
            }
        - script.execute: select_slot

  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    name: "Slot 2 Button"
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      then:
        - lambda: |-
            if (id(active_slot) == 1) {
              id(active_slot) = 254;
              id(active_slot_select).publish_state("External");
            } else {
              id(active_slot) = 1;
              id(active_slot_select).publish_state("2");
            }
        - script.execute: select_slot

  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
    name: "Slot 3 Button"
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      then:
        - lambda: |-
            if (id(active_slot) == 2) {
              id(active_slot) = 254;
              id(active_slot_select).publish_state("External");
            } else {
              id(active_slot) = 2;
              id(active_slot_select).publish_state("3");
            }
        - script.execute: select_slot


  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "Slot 4 Button"
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      then:
        - lambda: |-
            if (id(active_slot) == 3) {
              id(active_slot) = 254;
              id(active_slot_select).publish_state("External");
            } else {
              id(active_slot) = 3;
              id(active_slot_select).publish_state("4");
            }
        - script.execute: select_slot
