---
# NOTE None of these metrics are available until device is connected to MQTT
# This feels like a bug, but not sure why
debug:
  update_interval: 5s

text_sensor:
# Note that this only returns the esphome compiled version
# It does not return esphome.platform.version, as that value is only available through the api
# - platform: version
#   name: "Current Firmware Version"
#   hide_timestamp: true
#   state_topic:
#   # web_server:
#   #   sorting_group_id: sorting_group_info
- platform: template
  name: "OpenSpool Version"
  id: openspool_version
  state_topic:
  lambda: |-
    return to_string(ESPHOME_PROJECT_VERSION);
  icon: mdi:new-box
  web_server:
    sorting_group_id: sorting_group_info
- platform: debug
  reset_reason:
    name: "Reset Reason"
    id: reset_reason
    #state_topic:
sensor:
- platform: debug
  free:
    name: "Heap Free"
    id: heap_free
    #state_topic:
  block:
    name: "Heap Max Block"
    id: heap_max_block
    # state_topic:
    #   loop_time:
    #     name: "Loop Time"
    #     id: loop_time
    #     state_topic:
