esp32:
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0 # https://github.com/platformio/platform-espressif32/releases/
    sdkconfig_options:
      CONFIG_MBEDTLS_HKDF_C: y # Needed for bambu KDF
      CONFIG_MBEDTLS_MD_C: y   # Needed for bambu KDF
    # version: recommended
    # sdkconfig_options:
    # MBEDTLS_CERTIFICATE_BUNDLE: y
    # MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL: y

packages:
  led-external: !include conf.d/led-external.yaml

substitutions:
  mqtt: "mqtt"
