esp32:
  board: lolin_s2_mini

substitutions:
  hide_ams_sensors: 'true'
  led_pin: GPIO16
  spi2_type: SPI2 #SPI2,SPI3,any,hardware
  spi2_clk_pin: GPIO36
  spi2_miso_pin: GPIO37
  spi2_mosi_pin: GPIO35
  rfid0_spi_interface: SPI2
  rfid0_ss_pin: GPIO34
  #rfid1_spi_interface: SPI2
  #rfid1_ss_pin: GPIO21
  ## rfid1_spi_interface: SPI2
  ## rfid1_ss_pin: GPIO08

# D1 Mini S2 Boards will reboot when doing tasks like writing to PN532 unless wifi power is reduced
wifi:
  output_power: 10 # https://github.com/esphome/issues/issues/3988#issuecomment-1449954758
  
packages: 
  openspool-mini: !include openspool-mini.yaml
  #improv-serial: !include conf.d/improv-serial.yaml
  #extra: !include conf.d/extra.yaml
  button: !include conf.d/button.yaml
  esp32-common: !include esp32_common.yaml


dashboard_import:
  package_import_url: github://spuder/openspool/firmware/lolin_s2_mini.yaml@main
  import_full_config: false